#!/usr/bin/env python

import random
import sys

if __name__ == '__main__':
    if len(sys.argv) > 1:
        length = int(sys.argv[1])
    else:
        length = 4
    with open('/usr/share/dict/words') as file:
        words = file.readlines()
        print(" ".join(random.choice(words).strip() for x in range(length)))
